sudo: required
language: bash
services:
- docker
env:
- DOCKER_IMAGE_NAME=webitel/freeswitch
before_install:
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
install:
- docker build --no-cache -t $DOCKER_IMAGE_NAME .
script:
- docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:1.10.0
- docker push $DOCKER_IMAGE_NAME
- docker push $DOCKER_IMAGE_NAME:1.10.0
